Vagrant.configure("2") do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'

  config.vm.define "GOAD-ROUTER" do |router|
    router.vm.box = "bento/debian-11"
    router.vm.hostname = "goad-router"
    router.vm.synced_folder '.', '/vagrant', disabled: true
    router.vm.communicator = "ssh"

    router.vm.provider "vmware_desktop" do |v|
      v.force_vmware_license = "workstation"
      v.vmx["memsize"] = "768"
      v.vmx["numvcpus"] = "1"

      # Adapter 0 is Vagrant NAT for provisioning/SSH.
      # vagrant-vmware-desktop accepts :nat/:hostonly/:bridged as input types.
      # For an explicit existing vmnet, :nat + :device is normalized by the
      # provider into VMware connectionType="custom" with vnet="vmnetXX".
      # auto_config=false leaves guest addressing to provision.sh.
      v.network_adapter(1, :nat, { :device => "vmnet10", :mac_address => "00:50:56:10:10:01", :auto_config => false })
      v.network_adapter(2, :nat, { :device => "vmnet20", :mac_address => "00:50:56:10:20:01", :auto_config => false })
      v.network_adapter(3, :nat, { :device => "vmnet30", :mac_address => "00:50:56:10:30:01", :auto_config => false })
      v.network_adapter(4, :nat, { :device => "vmnet99", :mac_address => "00:50:56:10:99:01", :auto_config => false })
    end

    router.vm.provision :shell, :path => "provision.sh", privileged: true
  end
end
