#!/usr/bin/env bash
set -euo pipefail

# GOAD_NOMAD VMware Workstation host network bootstrap.
#
# Creates only the project-owned networks and preserves all existing VMware
# networking (for example the default vmnet1 host-only and vmnet8 NAT networks).
#
# Project networks:
#   vmnet10  NORTH           10.4.10.0/24   host adapter: yes
#   vmnet20  SEVENKINGDOMS   10.4.20.0/24   host adapter: no
#   vmnet30  ESSOS           10.4.30.0/24   host adapter: no
#   vmnet99  MANAGEMENT      10.4.99.0/24   host adapter: yes (provisioning)
#
# DHCP and VMware NAT are disabled on all four networks. Routing between
# exercise networks is performed only by GOAD-ROUTER.

readonly NETWORKING_FILE="/etc/vmware/networking"
readonly BACKUP_ROOT="/etc/vmware/goad-nomad-backups"
readonly VMWARE_NETWORKS="/usr/bin/vmware-networks"

fail() {
  echo "[!] $*" >&2
  exit 1
}

[[ ${EUID} -eq 0 ]] || fail "Run this script with sudo."
[[ -x "${VMWARE_NETWORKS}" ]] || fail "${VMWARE_NETWORKS} was not found. Is VMware Workstation installed?"
[[ -f "${NETWORKING_FILE}" ]] || fail "${NETWORKING_FILE} was not found. Start VMware Workstation once so networking is initialized."
command -v python3 >/dev/null 2>&1 || fail "python3 is required to edit VMware networking safely."

# Do not change the host networking underneath running VMware guests.
if pgrep -x vmware-vmx >/dev/null 2>&1; then
  fail "VMware virtual machines are running. Shut them down before changing vmnet configuration."
fi

stamp="$(date +%Y%m%d-%H%M%S)"
backup_dir="${BACKUP_ROOT}/${stamp}"
install -d -m 0700 "${backup_dir}"
cp -a "${NETWORKING_FILE}" "${backup_dir}/networking"
if [[ -f /etc/vmware/netmap.conf ]]; then
  cp -a /etc/vmware/netmap.conf "${backup_dir}/netmap.conf"
fi

echo "[*] Backed up VMware networking to ${backup_dir}"
echo "[*] Stopping VMware virtual networking"
"${VMWARE_NETWORKS}" --stop || true

python3 - "${NETWORKING_FILE}" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
text = path.read_text()
lines = text.splitlines()

# Remove only keys belonging to GOAD_NOMAD-owned vmnets. Everything else,
# including vmnet1/vmnet8 and bridge mappings, is preserved byte-for-byte as
# far as practical.
owned = {10, 20, 30, 99}
pattern = re.compile(r"^answer\s+VNET_(\d+)_")
kept = []
for line in lines:
    match = pattern.match(line)
    if match and int(match.group(1)) in owned:
        continue
    kept.append(line)

# Host adapter policy matters for the training model:
# - NORTH is intentionally reachable from the student's host.
# - SEVENKINGDOMS and ESSOS must not gain host-side adapters because that
#   would bypass the router/pivoting model.
# - MANAGEMENT is host-visible only as a provisioning/control plane and will
#   be disabled/restricted for exercise mode in a later milestone.
networks = {
    10: ("10.4.10.0", "yes", "NORTH"),
    20: ("10.4.20.0", "no",  "SEVENKINGDOMS"),
    30: ("10.4.30.0", "no",  "ESSOS"),
    99: ("10.4.99.0", "yes", "MANAGEMENT"),
}

if kept and kept[-1] != "":
    kept.append("")
kept.append("# GOAD_NOMAD managed networks - generated by scripts/setup-vmware-networks.sh")
for number, (subnet, host_adapter, label) in networks.items():
    kept.append(f"# vmnet{number}: {label}")
    kept.append(f"answer VNET_{number}_DHCP no")
    kept.append(f"answer VNET_{number}_HOSTONLY_NETMASK 255.255.255.0")
    kept.append(f"answer VNET_{number}_HOSTONLY_SUBNET {subnet}")
    kept.append(f"answer VNET_{number}_VIRTUAL_ADAPTER {host_adapter}")

path.write_text("\n".join(kept) + "\n")
PY

echo "[*] Starting VMware virtual networking"
if ! "${VMWARE_NETWORKS}" --start; then
  echo "[!] VMware networking failed to start. Restoring backup." >&2
  cp -a "${backup_dir}/networking" "${NETWORKING_FILE}"
  "${VMWARE_NETWORKS}" --start || true
  fail "Configuration was rolled back."
fi

echo
echo "[+] GOAD_NOMAD VMware networks configured"
echo "    vmnet10  NORTH           10.4.10.0/24   DHCP=off NAT=off host-adapter=yes"
echo "    vmnet20  SEVENKINGDOMS   10.4.20.0/24   DHCP=off NAT=off host-adapter=no"
echo "    vmnet30  ESSOS           10.4.30.0/24   DHCP=off NAT=off host-adapter=no"
echo "    vmnet99  MANAGEMENT      10.4.99.0/24   DHCP=off NAT=off host-adapter=yes"
echo
echo "[*] Existing VMware networks were preserved."
echo "[*] Backup: ${backup_dir}"
