#!/usr/bin/env bash
set -euo pipefail

# GOAD_NOMAD VMware Workstation host network bootstrap.
#
# Creates only the project-owned networks and preserves all existing VMware
# networking (for example the default vmnet1 host-only and vmnet8 NAT networks).
#
# Project networks:
#   vmnet10  NORTH           10.4.10.0/24   host adapter: 10.4.10.254
#   vmnet20  SEVENKINGDOMS   10.4.20.0/24   host adapter: none
#   vmnet30  ESSOS           10.4.30.0/24   host adapter: none
#   vmnet99  MANAGEMENT      10.4.99.0/24   host adapter: 10.4.99.254
#
# DHCP and VMware NAT are disabled on all four networks. Routing between
# exercise networks is performed only by GOAD-ROUTER, whose gateway addresses
# are .1 on each subnet.

readonly NETWORKING_FILE="/etc/vmware/networking"
readonly BACKUP_ROOT="/etc/vmware/goad-nomad-backups"
readonly VMWARE_NETWORKS="/usr/bin/vmware-networks"
readonly HOSTADDR_HELPER="/usr/local/sbin/goad-nomad-vmnet-hostaddrs"
readonly HOSTADDR_SERVICE="/etc/systemd/system/goad-nomad-vmnet-hostaddrs.service"
readonly HOSTADDR_TIMER="/etc/systemd/system/goad-nomad-vmnet-hostaddrs.timer"

fail() {
  echo "[!] $*" >&2
  exit 1
}

[[ ${EUID} -eq 0 ]] || fail "Run this script with sudo."
[[ -x "${VMWARE_NETWORKS}" ]] || fail "${VMWARE_NETWORKS} was not found. Is VMware Workstation installed?"
[[ -f "${NETWORKING_FILE}" ]] || fail "${NETWORKING_FILE} was not found. Start VMware Workstation once so networking is initialized."
command -v python3 >/dev/null 2>&1 || fail "python3 is required to edit VMware networking safely."
command -v ip >/dev/null 2>&1 || fail "iproute2 is required."

# Do not change the host networking underneath running VMware guests.
if pgrep -x vmware-vmx >/dev/null 2>&1; then
  fail "VMware virtual machines are running. Shut them down before changing vmnet configuration."
fi

stamp="$(date +%Y%m%d-%H%M%S)"
backup_dir="${BACKUP_ROOT}/${stamp}"
install -d -m 0700 "${backup_dir}"
cp -a "${NETWORKING_FILE}" "${backup_dir}/networking"
if [[ -f /etc/vmware/netmap.conf ]]; then
  cp -a /etc/vmware/netmap.conf "${backup_dir}/netmap.conf"
fi

echo "[*] Backed up VMware networking to ${backup_dir}"
echo "[*] Stopping VMware virtual networking"
"${VMWARE_NETWORKS}" --stop || true

python3 - "${NETWORKING_FILE}" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
text = path.read_text()
lines = text.splitlines()

# Remove only keys belonging to GOAD_NOMAD-owned vmnets. Everything else,
# including vmnet1/vmnet8 and bridge mappings, is preserved.
owned = {10, 20, 30, 99}
pattern = re.compile(r"^answer\s+VNET_(\d+)_")
kept = []
for line in lines:
    match = pattern.match(line)
    if match and int(match.group(1)) in owned:
        continue
    kept.append(line)

# Host adapter policy matters for the training model:
# - NORTH is intentionally reachable from the student's host.
# - SEVENKINGDOMS and ESSOS must not gain host-side adapters because that
#   would bypass the router/pivoting model.
# - MANAGEMENT is host-visible only as a provisioning/control plane and will
#   be disabled/restricted for exercise mode in a later milestone.
#
# Host-visible adapters use .254 so they never collide with GOAD-ROUTER (.1).
networks = {
    10: {"subnet": "10.4.10.0", "host_adapter": "yes", "host_addr": "10.4.10.254", "label": "NORTH"},
    20: {"subnet": "10.4.20.0", "host_adapter": "no",  "host_addr": None,          "label": "SEVENKINGDOMS"},
    30: {"subnet": "10.4.30.0", "host_adapter": "no",  "host_addr": None,          "label": "ESSOS"},
    99: {"subnet": "10.4.99.0", "host_adapter": "yes", "host_addr": "10.4.99.254", "label": "MANAGEMENT"},
}

if kept and kept[-1] != "":
    kept.append("")
kept.append("# GOAD_NOMAD managed networks - generated by scripts/setup-vmware-networks.sh")
for number, cfg in networks.items():
    kept.append(f"# vmnet{number}: {cfg['label']}")
    kept.append(f"answer VNET_{number}_DHCP no")
    # Workstation 26 may later strip HOSTONLY_HOSTADDR from this file. Keep it
    # as desired-state metadata, while the systemd helper below is authoritative
    # for the live host interface address.
    if cfg["host_addr"]:
        kept.append(f"answer VNET_{number}_HOSTONLY_HOSTADDR {cfg['host_addr']}")
    kept.append(f"answer VNET_{number}_HOSTONLY_NETMASK 255.255.255.0")
    kept.append(f"answer VNET_{number}_HOSTONLY_SUBNET {cfg['subnet']}")
    kept.append(f"answer VNET_{number}_VIRTUAL_ADAPTER {cfg['host_adapter']}")

path.write_text("\n".join(kept) + "\n")
PY

echo "[*] Starting VMware virtual networking"
if ! "${VMWARE_NETWORKS}" --start; then
  echo "[!] VMware networking failed to start. Restoring backup." >&2
  cp -a "${backup_dir}/networking" "${NETWORKING_FILE}"
  "${VMWARE_NETWORKS}" --start || true
  fail "Configuration was rolled back."
fi

# Workstation 26 can recreate host-only adapters during later Vagrant/VMware
# operations and drop manually assigned IPv4 addresses. The helper is
# idempotent: it changes an interface only when the expected address is absent.
cat > "${HOSTADDR_HELPER}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

configure_addr() {
  local iface="$1" cidr="$2"
  local i

  for i in $(seq 1 20); do
    if ip link show "${iface}" >/dev/null 2>&1; then
      ip link set dev "${iface}" up
      if ip -4 -o addr show dev "${iface}" | awk '{print $4}' | grep -Fxq "${cidr}"; then
        return 0
      fi
      ip -4 addr flush dev "${iface}"
      ip -4 addr add "${cidr}" dev "${iface}"
      return 0
    fi
    sleep 1
  done

  echo "[!] ${iface} did not appear within 20 seconds" >&2
  return 1
}

configure_addr vmnet10 10.4.10.254/24
configure_addr vmnet99 10.4.99.254/24
EOF
chmod 0755 "${HOSTADDR_HELPER}"

cat > "${HOSTADDR_SERVICE}" <<'EOF'
[Unit]
Description=GOAD_NOMAD VMware host-only interface addresses
After=network.target vmware.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/goad-nomad-vmnet-hostaddrs
EOF

cat > "${HOSTADDR_TIMER}" <<'EOF'
[Unit]
Description=Keep GOAD_NOMAD VMware host-only addresses present
After=vmware.service

[Timer]
OnBootSec=3s
OnUnitActiveSec=15s
AccuracySec=1s
Unit=goad-nomad-vmnet-hostaddrs.service
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
# Remove the older RemainAfterExit service enablement if it exists.
systemctl disable goad-nomad-vmnet-hostaddrs.service >/dev/null 2>&1 || true
systemctl enable --now goad-nomad-vmnet-hostaddrs.timer >/dev/null
# Apply desired addresses immediately rather than waiting for the first timer tick.
systemctl start goad-nomad-vmnet-hostaddrs.service

echo
echo "[+] GOAD_NOMAD VMware networks configured"
echo "    vmnet10  NORTH           10.4.10.0/24   host=10.4.10.254 DHCP=off NAT=off"
echo "    vmnet20  SEVENKINGDOMS   10.4.20.0/24   host=none        DHCP=off NAT=off"
echo "    vmnet30  ESSOS           10.4.30.0/24   host=none        DHCP=off NAT=off"
echo "    vmnet99  MANAGEMENT      10.4.99.0/24   host=10.4.99.254 DHCP=off NAT=off"
echo
echo "[*] Existing VMware networks were preserved."
echo "[*] Backup: ${backup_dir}"
echo "[*] Host-address persistence: goad-nomad-vmnet-hostaddrs.timer"
